using System.IO;
using System.Text;
using Translator.Core.IO;

namespace Translator.Core.CodeGen;

/// <summary>
/// Generates runtime configuration metadata for the C++ runtime harness.
/// This includes critical architectural values like SDA base pointers that
/// must be initialized before any translated code can execute.
/// </summary>
public sealed class RuntimeConfigGenerator
{
    /// <summary>
    /// Generates a C++ header file containing runtime configuration metadata. SDA bases come from the
    /// project manifest, not from scanning the boot code: they're data pinned to the DOL's SHA-256, and
    /// guessing them from section midpoints could silently produce a wrong runtime.
    /// </summary>
    public static void GenerateConfigHeader(
        uint sda1Base,
        uint sda2Base,
        uint entryPoint,
        string outputPath,
        string projectName = "PowerPC DOL",
        string? gameId = null,
        string guestPlatform = "wii")
    {
        static uint PackAscii(string? text, int offset, int count)
        {
            if (string.IsNullOrEmpty(text) || text.Length < offset + count)
            {
                return 0;
            }

            uint value = 0;
            for (var i = 0; i < count; i++)
            {
                var ch = text[offset + i];
                if (ch > 0x7f)
                {
                    return 0;
                }
                value = (value << 8) | ch;
            }
            return value;
        }

        var gameCode = PackAscii(gameId, 0, 4);
        var makerCode = PackAscii(gameId, 4, 2);
        var normalizedPlatform = guestPlatform.Trim().ToLowerInvariant();
        if (normalizedPlatform is not ("wii" or "gamecube"))
        {
            throw new ArgumentException(
                $"Unsupported guest platform '{guestPlatform}'. Expected 'wii' or 'gamecube'.",
                nameof(guestPlatform));
        }
        var isWii = normalizedPlatform == "wii";
        var sb = new StringBuilder();
        sb.AppendLine($"// AUTO-GENERATED for {projectName}");
        sb.AppendLine("// DO NOT EDIT THIS FILE MANUALLY");
        sb.AppendLine("//");
        sb.AppendLine("// The runtime loads these into r2/r13 before executing any translated code.");
        sb.AppendLine();
        sb.AppendLine("#pragma once");
        sb.AppendLine();
        sb.AppendLine("#include <cstdint>");
        sb.AppendLine();
        sb.AppendLine("namespace RuntimeConfig {");
        sb.AppendLine();
        sb.AppendLine("// PowerPC ABI Small Data Area base pointers");
        sb.AppendLine("// These MUST be loaded into r2 and r13 before executing any translated code.");
        sb.AppendLine();

        // SDA1 (r13) - read/write small data
        sb.AppendLine($"// _SDA_BASE_ (r13): Base pointer for .sdata/.sbss sections");
        sb.AppendLine($"constexpr uint32_t SDA1_BASE = 0x{sda1Base:X8}u;  // memory.sda_base");
        sb.AppendLine();

        // SDA2 (r2) - read-only small data
        sb.AppendLine($"// _SDA2_BASE_ (r2): Base pointer for .sdata2/.sbss2 sections");
        sb.AppendLine($"constexpr uint32_t SDA2_BASE = 0x{sda2Base:X8}u;  // memory.sda2_base");
        sb.AppendLine();

        sb.AppendLine("// DOL entry point used by the native runtime bootstrap");
        sb.AppendLine($"constexpr uint32_t ENTRY_POINT = 0x{entryPoint:X8}u;");
        sb.AppendLine();

        sb.AppendLine("// Disc identity from project.game_id. Generic-DOL boot uses these instead of MKW defaults.");
        sb.AppendLine($"constexpr uint32_t GAME_CODE = 0x{gameCode:X8}u;");
        sb.AppendLine($"constexpr uint16_t MAKER_CODE = 0x{makerCode:X4}u;");
        sb.AppendLine();

        sb.AppendLine("// Guest console platform from project.platform.");
        sb.AppendLine($"constexpr const char* GUEST_PLATFORM = \"{normalizedPlatform}\";");
        sb.AppendLine($"constexpr bool IS_WII = {(isWii ? "true" : "false")};");
        sb.AppendLine($"constexpr bool IS_GAMECUBE = {(isWii ? "false" : "true")};");
        sb.AppendLine();


        sb.AppendLine("} // namespace RuntimeConfig");
        sb.AppendLine();

        Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);
        FileOutput.WriteTextIfChanged(outputPath, sb.ToString());
    }
}
