#include "system_bridge.h"

#include <algorithm>
#include <cctype>
#include <cstring>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <optional>
#include <limits>
#include <sstream>
#include <string>
#include <vector>

#if defined(_WIN32)
#ifndef NOMINMAX
#define NOMINMAX
#endif
#include <windows.h>
#endif


#include "abi_bridge.h"
#include "memory.h"
#include "ppc_runtime.h"
#include "recomp_mod_loader.h"
#include "runtime_config.h"
#include "runtime_log.h"
#include "runtime_product.h"
#include "timebase_contract.h"
#include "wiicompiled_target.h"
#include "RuntimeConfig.h"

// Global flag to suppress SEH reporting during static constructor execution
bool g_suppressSehReporting = false;
thread_local MkwJmpBuf* g_sehJumpTarget = nullptr;
thread_local uint32_t g_sehLastExceptionCode = 0;
thread_local uintptr_t g_sehLastExceptionAddress = 0;
thread_local uintptr_t g_sehLastAccessedAddress = 0;
thread_local uint32_t g_sehLastAccessType = 0;

// Forward declaration for data section initialization generated by the translator.
extern "C" void InitializeDataSections();

namespace {
std::string Hex32(uint32_t value) {
    std::ostringstream oss;
    oss << std::hex << std::uppercase << std::setw(8) << std::setfill('0') << value;
    return oss.str();
}

std::optional<std::string> PrintableU32(uint32_t value) {
    std::string out;
    out.reserve(4);
    for (int shift = 24; shift >= 0; shift -= 8) {
        const auto ch = static_cast<unsigned char>((value >> shift) & 0xFFu);
        if (!std::isprint(ch)) {
            return std::nullopt;
        }
        out.push_back(static_cast<char>(ch));
    }
    return out;
}

#if defined(MKW_GENERIC_DOL_BOOT)
struct GenericWiiBootState {
    uint32_t legacyArenaHi = 0;
    uint32_t postApploaderArenaHi = 0;
    uint32_t bi2Address = 0;
    std::vector<uint8_t> bi2;
};

#if WIICOMPILED_GUEST_IS_GAMECUBE
struct GenericGameCubeBootState {
    uint32_t arenaHi = 0;
    uint32_t fstAddress = 0;
    uint32_t fstMaxSize = 0;
    std::vector<uint8_t> fst;
};
#endif

uint32_t ReadHostBe32(const uint8_t* bytes) {
    return (static_cast<uint32_t>(bytes[0]) << 24) |
           (static_cast<uint32_t>(bytes[1]) << 16) |
           (static_cast<uint32_t>(bytes[2]) << 8) |
           static_cast<uint32_t>(bytes[3]);
}

std::optional<std::vector<uint8_t>> ReadHostFile(const std::filesystem::path& path) {
    std::ifstream input(path, std::ios::binary | std::ios::ate);
    if (!input) {
        return std::nullopt;
    }
    const std::streamsize size = input.tellg();
    if (size < 0) {
        return std::nullopt;
    }
    std::vector<uint8_t> bytes(static_cast<size_t>(size));
    input.seekg(0, std::ios::beg);
    if (size != 0 && !input.read(reinterpret_cast<char*>(bytes.data()), size)) {
        return std::nullopt;
    }
    return bytes;
}

struct GenericWiiIosBootState {
    uint32_t iosNumber = 0;
    uint32_t iosVersion = 0;
    uint32_t iosDate = 0;
};

std::optional<GenericWiiIosBootState> LoadGenericWiiIosBootState() {
    const std::filesystem::path dvdRoot = RuntimeConfigFile::ResolvedDvdRoot();
    if (dvdRoot.empty()) {
        return std::nullopt;
    }

    const auto tmd = ReadHostFile(dvdRoot / "tmd.bin");
    // Disc TMDs use the RSA-2048 signed layout. sys_version is the u64 at
    // 0x184; Wii IOS title IDs are 00000001-000000xx.
    if (!tmd || tmd->size() < 0x18Cu || ReadHostBe32(tmd->data() + 0x184) != 1u) {
        return std::nullopt;
    }

    const uint32_t iosNumber = ReadHostBe32(tmd->data() + 0x188);
    GenericWiiIosBootState state{};
    state.iosNumber = iosNumber;

    // IOS kernel low-memory values from the same RVL IOS binaries represented
    // by Dolphin's VersionInfo table. Add entries here as generic-DOL titles
    // requiring other IOSes are brought up; never pretend a different IOS is
    // running just to satisfy an SDK compatibility check.
    switch (iosNumber) {
    case 36u:
        state.iosVersion = 0x00240E18u;
        state.iosDate = 0x00030110u;
        break;
    case 55u:
        state.iosVersion = 0x0037161Fu;
        state.iosDate = 0x00030110u;
        break;
    default:
        RT_LOG(RT_TAG_RUNTIME) << "Generic Wii boot: TMD requires IOS" << iosNumber
                               << "; no low-memory IOS version profile is available yet"
                               << std::endl;
        return std::nullopt;
    }

    return state;
}
std::optional<GenericWiiBootState> LoadGenericWiiBootState(uint32_t mem1End) {
    // A direct-DOL recomp starts after BS2/apploader would have run on hardware.
    // Reconstruct only the low-memory inputs that SDK OSInit consumes from the
    // extracted disc's own boot metadata instead of inventing a title heap size.
    const std::filesystem::path dvdRoot = RuntimeConfigFile::ResolvedDvdRoot();
    if (dvdRoot.empty()) {
        return std::nullopt;
    }

    const auto boot = ReadHostFile(dvdRoot / "sys" / "boot.bin");
    const auto bi2 = ReadHostFile(dvdRoot / "sys" / "bi2.bin");
    if (!boot || boot->size() < 0x430 || !bi2 || bi2->empty()) {
        return std::nullopt;
    }

    // boot.bin stores FST size/max-size in 32-bit words at 0x428/0x42C.
    // The apploader reserves the maximum from the top of MEM1 and aligns the
    // resulting arena high down to 32 bytes before publishing 0x80003110.
    uint32_t fstWords = ReadHostBe32(boot->data() + 0x42C);
    if (fstWords == 0) {
        fstWords = ReadHostBe32(boot->data() + 0x428);
    }
    const uint64_t fstBytes = static_cast<uint64_t>(fstWords) * 4u;
    if (fstBytes == 0 || fstBytes >= mem1End - Memory::kMem1CachedBase) {
        return std::nullopt;
    }

    GenericWiiBootState state;
    // Wii BS2's normal pre-apploader MEM1 arena high. The apploader-published
    // 0x80003110 below takes precedence in OSInit, but keeping the legacy word
    // models the boot contract faithfully for other SDK readers.
    state.legacyArenaHi = 0x817FEC60u;
    state.postApploaderArenaHi =
        static_cast<uint32_t>((static_cast<uint64_t>(mem1End) - fstBytes) & ~0x1Full);
    // Wii BS2 places BI2 here and publishes this pointer at 0x800000F4. WOS
    // reads BI2+0x0C before selecting its linked-image ArenaLo.
    state.bi2Address = 0x8179B500u;
    state.bi2 = *bi2;

    if (state.postApploaderArenaHi <= Memory::kMem1CachedBase ||
        state.postApploaderArenaHi > mem1End ||
        !Memory::Contains(state.bi2Address, state.bi2.size())) {
        return std::nullopt;
    }
    return state;
}

#if WIICOMPILED_GUEST_IS_GAMECUBE
std::optional<GenericGameCubeBootState> LoadGenericGameCubeBootState(uint32_t mem1End) {
    // A direct GameCube DOL starts after BS2/apploader. On hardware the
    // apploader has already copied the disc FST into MEM1, lowered ArenaHi so
    // the title cannot allocate over it, and published its address/max size at
    // 0x80000038/0x8000003C. Recreate that boot contract from the extracted
    // disc metadata rather than waiting for DVDInit inside the title.
    const std::filesystem::path dvdRoot = RuntimeConfigFile::ResolvedDvdRoot();
    if (dvdRoot.empty()) {
        return std::nullopt;
    }

    const auto boot = ReadHostFile(dvdRoot / "sys" / "boot.bin");
    const auto fst = ReadHostFile(dvdRoot / "sys" / "fst.bin");
    if (!boot || boot->size() < 0x430 || !fst || fst->empty()) {
        return std::nullopt;
    }

    if (fst->size() > std::numeric_limits<uint32_t>::max()) {
        return std::nullopt;
    }
    const uint32_t bootFstSize = ReadHostBe32(boot->data() + 0x428);
    uint32_t fstMaxSize = ReadHostBe32(boot->data() + 0x42C);
    if (fstMaxSize == 0) {
        fstMaxSize = bootFstSize;
    }
    fstMaxSize = std::max<uint32_t>(fstMaxSize, static_cast<uint32_t>(fst->size()));
    if (fstMaxSize == 0 || fstMaxSize >= mem1End - Memory::kMem1CachedBase) {
        return std::nullopt;
    }

    const uint32_t unaligned = mem1End - fstMaxSize;
    const uint32_t fstAddress = unaligned & ~0x1Fu;
    if (fstAddress <= Memory::kMem1CachedBase ||
        !Memory::Contains(fstAddress, fstMaxSize)) {
        return std::nullopt;
    }

    GenericGameCubeBootState state;
    state.arenaHi = fstAddress;
    state.fstAddress = fstAddress;
    state.fstMaxSize = fstMaxSize;
    state.fst = *fst;
    return state;
}
#endif
#endif

std::optional<TranslatedFunctionInfo> FindNearestTranslatedFunction(uint32_t address) {
    auto best = TranslatedFunctionRegistry::FindNearestByAddress(address);

    // Crash-only heuristic: large gaps are usually data/FourCC values, not code offsets.
    if (best && address - best->address < 0x10000u) {
        return best;
    }
    return std::nullopt;
}

// generated/guest_symbol_table.cpp (or the stub when it is absent): the
// project's function-map names, sorted by address, for crash symbolization.
extern "C" {
extern const uint32_t kGuestMapSymbolCount;
extern const uint32_t kGuestMapSymbolAddresses[];
extern const char* const kGuestMapSymbolNames[];
}

// Floor lookup into the function-map name table with the same gap cap as the
// registry heuristic above. Returns nullptr when no named symbol is close.
const char* GuestMapSymbolFloor(uint32_t address, uint32_t* symbolStart) {
    if (kGuestMapSymbolCount == 0) {
        return nullptr;
    }
    uint32_t lo = 0;
    uint32_t hi = kGuestMapSymbolCount;
    while (lo < hi) {
        const uint32_t mid = lo + (hi - lo) / 2;
        if (kGuestMapSymbolAddresses[mid] <= address) {
            lo = mid + 1;
        } else {
            hi = mid;
        }
    }
    if (lo == 0) {
        return nullptr;
    }
    const uint32_t index = lo - 1;
    if (address - kGuestMapSymbolAddresses[index] >= 0x10000u) {
        return nullptr;
    }
    if (symbolStart) {
        *symbolStart = kGuestMapSymbolAddresses[index];
    }
    return kGuestMapSymbolNames[index];
}

std::optional<uint32_t> ReadGuest32NoThrow(uint32_t address) {
    uint32_t value = 0;
    if (MemoryInline::TryReadMappedScalar(address, value)) {
        return value;
    }
    return std::nullopt;
}

std::optional<uint8_t> ReadGuest8NoThrow(uint32_t address) {
    uint8_t value = 0;
    if (MemoryInline::TryReadMappedScalar(address, value)) {
        return value;
    }
    return std::nullopt;
}

std::optional<std::string> GuestCStringPreview(uint32_t address) {
    std::string out;
    out.reserve(48);
    for (uint32_t i = 0; i < 48; ++i) {
        const auto byte = ReadGuest8NoThrow(address + i);
        if (!byte) {
            return std::nullopt;
        }
        if (*byte == 0) {
            return out.size() >= 3 ? std::optional<std::string>(out) : std::nullopt;
        }
        if (!std::isprint(*byte)) {
            return std::nullopt;
        }
        out.push_back(static_cast<char>(*byte));
    }
    out += "...";
    return out;
}

void PrintGuestValue(std::ostream& os, std::string_view label, uint32_t value) {
    os << " ";
    if (!label.empty()) {
        os << label << "=";
    }
    os << "0x" << Hex32(value);
    // Prefer the function-map name (human symbol) over the registry's
    // func_XXXXXXXX label; when both resolve, the closer floor wins so a map
    // symbol from a preceding function cannot shadow an exact registry hit.
    uint32_t mapStart = 0;
    const char* mapName = GuestMapSymbolFloor(value, &mapStart);
    if (const auto* exact = TranslatedFunctionRegistry::FindByAddressPtr(value)) {
        if (mapName && mapStart >= exact->address) {
            os << "<" << mapName;
            if (value != mapStart) {
                os << "+0x" << std::hex << std::uppercase << (value - mapStart) << std::dec;
            }
            os << ">";
        } else {
            os << "<" << exact->name << ">";
        }
    } else if (auto nearest = FindNearestTranslatedFunction(value)) {
        if (mapName && mapStart >= nearest->address) {
            os << "<" << mapName;
            if (value != mapStart) {
                os << "+0x" << std::hex << std::uppercase << (value - mapStart) << std::dec;
            }
            os << ">";
        } else {
            os << "<" << nearest->name << "+0x" << std::hex << std::uppercase
               << (value - nearest->address) << std::dec << ">";
        }
    } else if (mapName) {
        os << "<" << mapName << "+0x" << std::hex << std::uppercase
           << (value - mapStart) << std::dec << ">";
    }
    if (auto text = PrintableU32(value)) {
        os << "('" << *text << "')";
    } else if (auto guestString = GuestCStringPreview(value)) {
        os << "(\"" << *guestString << "\")";
    }
}

void PrintFrameTailWords(std::ostream& os, uint32_t previousSp) {
    os << " tail:";
    for (int32_t offset = -0x40; offset <= 0x04; offset += 4) {
        const uint32_t address = previousSp + static_cast<uint32_t>(offset);
        const auto value = ReadGuest32NoThrow(address);
        if (!value) {
            continue;
        }
        os << " " << (offset < 0 ? "-" : "+")
           << std::hex << std::uppercase << std::setw(2) << std::setfill('0')
           << static_cast<uint32_t>(std::abs(offset)) << "=0x" << Hex32(*value);
    }
    os << std::dec << std::setfill(' ');
}

void DumpGuestBackchain(std::ostream& os, const CpuContext* cpu) {
    uint32_t sp = cpu->gpr[1];
    if (sp == 0) {
        return;
    }

    os << "[runtime] Stack backchain:" << std::endl;
    for (int frame = 0; frame < 12; ++frame) {
        const auto previousSp = ReadGuest32NoThrow(sp);
        if (!previousSp || *previousSp == 0) {
            os << "[runtime]   #" << frame << " sp=0x" << Hex32(sp) << " prev=(unmapped)" << std::endl;
            break;
        }

        const uint32_t frameSize = *previousSp - sp;
        os << "[runtime]   #" << frame << " sp=0x" << Hex32(sp)
           << " prev=0x" << Hex32(*previousSp)
           << " size=0x" << std::hex << std::uppercase << frameSize << std::dec;

        if (frameSize <= 0x20000u) {
            if (const auto savedLr = ReadGuest32NoThrow(*previousSp + 4u)) {
                PrintGuestValue(os, "savedLR", *savedLr);
            }
            PrintFrameTailWords(os, *previousSp);
        }
        os << std::endl;

        if (*previousSp <= sp || frameSize > 0x20000u) {
            break;
        }
        sp = *previousSp;
    }
}

void DumpGuestStackHints(std::ostream& os, const CpuContext* cpu) {
    const uint32_t sp = cpu->gpr[1];
    if (sp == 0) {
        return;
    }

    os << "[runtime] Stack words:";
    for (uint32_t offset = 0; offset < 0x40; offset += 4) {
        const auto value = ReadGuest32NoThrow(sp + offset);
        if (!value) {
            break;
        }
        os << " +" << std::hex << std::uppercase << std::setw(2) << std::setfill('0')
           << offset << "=0x" << Hex32(*value);
    }
    os << std::dec << std::setfill(' ') << std::endl;

    int printed = 0;
    for (uint32_t offset = 0; offset < 0x800 && printed < 32; offset += 4) {
        const auto value = ReadGuest32NoThrow(sp + offset);
        if (!value) {
            continue;
        }
        if (!TranslatedFunctionRegistry::FindByAddressPtr(*value) && !FindNearestTranslatedFunction(*value)) {
            continue;
        }
        if (printed == 0) {
            os << "[runtime] Stack code refs:";
        }
        os << " +" << std::hex << std::uppercase << offset << std::dec << ":";
        PrintGuestValue(os, "", *value);
        ++printed;
    }
    if (printed != 0) {
        os << std::endl;
    }
}

void DumpGuestCrashHints(std::ostream& os, const CpuContext* cpu) {
    if (!cpu) {
        return;
    }

    const uint32_t active = RecompMod::CurrentTranslatedExecutionAddress();
    if (active != 0) {
        os << "[runtime] Active translated target: ";
        PrintGuestValue(os, "guest", active);
        os << std::endl;
    }

    os << "[runtime] Guest refs:";
    PrintGuestValue(os, "pc", cpu->pc);
    PrintGuestValue(os, "lr", cpu->lr);
    PrintGuestValue(os, "ctr", cpu->ctr);
    PrintGuestValue(os, "r12", cpu->gpr[12]);
    PrintGuestValue(os, "r3", cpu->gpr[3]);
    PrintGuestValue(os, "r4", cpu->gpr[4]);
    PrintGuestValue(os, "r5", cpu->gpr[5]);
    PrintGuestValue(os, "r15", cpu->gpr[15]);
    PrintGuestValue(os, "r16", cpu->gpr[16]);
    PrintGuestValue(os, "r18", cpu->gpr[18]);
    PrintGuestValue(os, "r26", cpu->gpr[26]);
    PrintGuestValue(os, "r27", cpu->gpr[27]);
    os << std::endl;

    if (active != 0 && active != cpu->pc) {
        os << "[runtime] Note: active translated target differs from ctx->pc; ctx->pc may be stale "
              "without PC tracing."
           << std::endl;
    }

    DumpGuestStackHints(os, cpu);
    DumpGuestBackchain(os, cpu);
}

} // namespace

void SystemBridge::Initialize() {
#if WIICOMPILED_GUEST_IS_GAMECUBE
    auto memoryConfig = Memory::Config::GameCubeDefaults();
#else
    auto memoryConfig = Memory::Config::WiiDefaults();
#endif
#if defined(WIICOMPILED_APPLY_TITLE_MEMORY_CONFIG)
    WIICOMPILED_APPLY_TITLE_MEMORY_CONFIG(memoryConfig);
#elif defined(MKW_APPLY_TITLE_MEMORY_CONFIG)
    MKW_APPLY_TITLE_MEMORY_CONFIG(memoryConfig);
#endif
    Memory::Init(memoryConfig);

    SeedLowMemDefaults(memoryConfig);

    // Initialize from the embedded DOL/REL data sections. This provides the
    // initial memory state for .data, .rodata, .sdata, etc.
    RT_LOG(RT_TAG_RUNTIME) << "Initializing data sections from embedded DOL/REL data" << std::endl;
    InitializeDataSections();

    // Constructors run before the main entry point, but they still require the
    // PowerPC ABI environment. Keep using the persistent context here: the old
    // AbiCallContext path implicitly selected and seeded it for every ctor.
    InitializePersistentCpuContext();
    CpuContext& cpu = GetPersistentCpuContext();
    cpu.gpr[1] = 0x81700000u;
    CpuContextScope scope(&cpu);

    g_suppressSehReporting = true;

#if !defined(MKW_GENERIC_DOL_BOOT)

    // Run main DOL static constructors first
    // These set up vtables and other critical infrastructure
    RT_LOG(RT_TAG_RUNTIME) << "Running static constructors for main DOL..." << std::endl;

    const uint32_t dolCtorStart = 0x80244DE0;
    const uint32_t dolCtorEnd = 0x80244EA0;

    int dolCount = 0;
    for (uint32_t addr = dolCtorStart; addr < dolCtorEnd; addr += 4) {
        uint32_t funcAddr = 0;
        try {
            funcAddr = Memory::Read32(addr);
        } catch (...) {
            continue;
        }

        if (funcAddr == 0 || funcAddr == 0xFFFFFFFF) continue;

        if (TranslatedFunctionRegistry::FindByAddressPtr(funcAddr)) {
            MkwJmpBuf jumpBuf;
            g_sehJumpTarget = &jumpBuf;
            if (MKW_SETJMP(jumpBuf) == 0) {
                cpu.gpr[1] = 0x81700000u;
                InvokeIndirectCpu(funcAddr, &cpu);
                dolCount++;
            } else {
                RT_LOG(RT_TAG_RUNTIME) << "SEH Exception caught invoking DOL ctor 0x" << std::hex << funcAddr
                          << " code=0x" << g_sehLastExceptionCode
                          << " at=0x" << g_sehLastExceptionAddress;
                if (g_sehLastExceptionCode == 0xC0000005u && g_sehLastAccessedAddress != 0) {
                    std::cerr << " " << (g_sehLastAccessType ? "write" : "read")
                              << "=0x" << g_sehLastAccessedAddress;
                }
                std::cerr << std::dec << " - skipping." << std::endl;
            }
            g_sehJumpTarget = nullptr;
        }
    }
    RT_LOG(RT_TAG_RUNTIME) << "Executed " << dolCount << " main DOL static constructors." << std::endl;

    // StaticR.rel ctors must be run manually since we aren't using OSLink
    RT_LOG(RT_TAG_RUNTIME) << "Running static constructors for StaticR.rel..." << std::endl;

    // Define range for StaticR.rel .ctors
    const uint32_t ctorStart = 0x8088f400;
    const uint32_t ctorEnd = 0x8088f704;

    int count = 0;
    for (uint32_t addr = ctorStart; addr < ctorEnd; addr += 4) {
        uint32_t funcAddr = 0;
        try {
            funcAddr = Memory::Read32(addr);
        } catch (...) {
            continue;
        }

        if (funcAddr == 0 || funcAddr == 0xFFFFFFFF) continue;

        if (TranslatedFunctionRegistry::FindByAddressPtr(funcAddr)) {
            MkwJmpBuf jumpBuf;
            g_sehJumpTarget = &jumpBuf;
            if (MKW_SETJMP(jumpBuf) == 0) {
                cpu.gpr[1] = 0x81700000u;
                InvokeIndirectCpu(funcAddr, &cpu);
                count++;
            } else {
                RT_LOG(RT_TAG_RUNTIME) << "SEH Exception caught invoking ctor 0x" << std::hex << funcAddr
                          << " code=0x" << g_sehLastExceptionCode
                          << " at=0x" << g_sehLastExceptionAddress;
                if (g_sehLastExceptionCode == 0xC0000005u && g_sehLastAccessedAddress != 0) {
                    std::cerr << " " << (g_sehLastAccessType ? "write" : "read")
                              << "=0x" << g_sehLastAccessedAddress;
                }
                std::cerr << std::dec << " - skipping." << std::endl;
            }
            g_sehJumpTarget = nullptr;
        }
    }
    RT_LOG(RT_TAG_RUNTIME) << "Executed " << count << " static constructors." << std::endl;
#else
    RT_LOG(RT_TAG_RUNTIME) << "Generic DOL boot: constructor pre-run skipped; DOL entry point owns CRT initialization." << std::endl;
#endif
    g_suppressSehReporting = false;
}

void SystemBridge::WriteGuestMemorySnapshot(std::ostream& os, const std::filesystem::path& mem1Path) {
    constexpr uint32_t kMem1Base = 0x80000000u;
    constexpr uint32_t kMem1Size = 0x01800000u;
    if (Memory::Contains(kMem1Base, kMem1Size)) {
        std::ofstream dump(mem1Path, std::ios::binary | std::ios::trunc);
        dump.write(reinterpret_cast<const char*>(Memory::GetPointer(kMem1Base, kMem1Size)),
                   kMem1Size);
        os << "[runtime] MEM1 snapshot written to " << RuntimeConfigFile::PathToUtf8(mem1Path)
           << (dump.good() ? "" : " (write failed)") << std::endl;
    }
    constexpr uint32_t kMem2Base = 0x90000000u;
    for (uint32_t mem2Size : {0x08000000u, 0x04000000u}) {
        if (!Memory::Contains(kMem2Base, mem2Size)) {
            continue;
        }
        std::filesystem::path mem2Path = mem1Path;
        mem2Path += ".mem2";
        std::ofstream dump(mem2Path, std::ios::binary | std::ios::trunc);
        dump.write(reinterpret_cast<const char*>(Memory::GetPointer(kMem2Base, mem2Size)),
                   mem2Size);
        os << "[runtime] MEM2 snapshot written to " << RuntimeConfigFile::PathToUtf8(mem2Path)
           << (dump.good() ? "" : " (write failed)") << std::endl;
        break;
    }
}

void SystemBridge::DumpCrashHeuristics(std::ostream& os, const CpuContext* cpu,
                                       const uint32_t* missingGuestTarget) {
    if (!cpu) {
        return;
    }

    if (missingGuestTarget && *missingGuestTarget == 0) {
        os << "[runtime] The guest jumped to address 0 - almost always a virtual call "
              "through a bad object, or a callback pointer that was never set."
           << std::endl;
        if (cpu->gpr[3] == 0) {
            os << "[runtime] r3 (the C++ 'this' pointer) is NULL at the call. A very common "
                  "cause is an unchecked guest heap allocation failure: every "
                  "\"heap (...)->alloc(size(...))\" OSReport line above is a FAILED "
                  "allocation (the number after 'free' is the bytes actually left in "
                  "that heap). If those lines are present, the heap was exhausted "
                  "before this crash." << std::endl;
        }
    } else if (missingGuestTarget) {
        os << "[runtime] The guest jumped to 0x" << std::hex << std::uppercase
           << *missingGuestTarget << std::dec
           << ", which is not a translated function entry. If the value looks like "
              "readable text or a data pointer, a function pointer or vtable was "
              "overwritten (guest memory stomp)." << std::endl;
    }
}

// Boot-time guest space reserved for the runtime FST. Wii uses MEM2; direct
// GameCube DOL boots reserve the apploader FST at the top of MEM1.
extern "C" uint32_t g_dvdFstReservedBase = 0;
extern "C" uint32_t g_dvdFstReservedSize = 0;

void SystemBridge::SeedLowMemDefaults(const Memory::Config& config) {

    const auto* mem1Region = FindRegionConfig(config, "MEM1");
    const auto* mem2Region = FindRegionConfig(config, "MEM2");
    const uint32_t mem1Size = mem1Region ? static_cast<uint32_t>(mem1Region->sizeBytes) : 0;
    const uint32_t mem2Size = mem2Region ? static_cast<uint32_t>(mem2Region->sizeBytes) : 0;

    struct SeedEntry {
        uint32_t address;
        uint32_t value;
        const char* label;
        bool force = false;
    };

    std::vector<SeedEntry> entries;
#if defined(MKW_GENERIC_DOL_BOOT)
    // A generic DOL owns its arena layout.  In particular, SDK OSInit reads
    // 0x8000310C/0x80003110 and computes title-specific defaults when they are
    // zero.  Seeding Mario Kart Wii's linked arena here makes other titles use
    // MKW's 0x80399180 low bound; their ClearArena then wipes live .bss/stack.
    // Leave both legacy and MEM1 arena low/high words untouched for generic
    // boots and let the guest establish them from its own linked image.
    constexpr uint32_t kMem1ArenaLoDefault = 0u;
    uint32_t mem1ArenaHiDefault = 0u;
#if !WIICOMPILED_GUEST_IS_GAMECUBE
    std::optional<GenericWiiBootState> genericWiiBootState;
#endif
#else
    constexpr uint32_t kMem1ArenaLoDefault = 0x80399180u;
    uint32_t mem1ArenaHiDefault = 0x817f0520u;
#endif
    constexpr uint32_t kBusClockHz =
        static_cast<uint32_t>(TimeBaseContract::kBusClockHz);
    constexpr uint32_t kCpuClockHz = kBusClockHz * 3u;


    constexpr uint32_t kMem2LoFloor = 0x90000800u;
    // Reserve enough guest memory for the runtime-built DVD FST.
    constexpr uint32_t kDvdFstReserveSize = 0x200000u;
    // IOS36 reserves 128 KiB for IPC immediately below a 128 KiB IOS-owned
    // block. Dolphin's RAM override preserves both sizes and moves them to the
    // top of the expanded MEM2 mapping.
    constexpr uint32_t kIPCArenaSize = 0x20000u;
    constexpr uint32_t kIosReservedSize = 0x20000u;

    // The boot code exposes the current disc ID in low memory before DVDInit.
    // Retro Rewind reads the region byte directly from here while building its
    // Retro-WFC payload URL, and OSGetAppGamename reads the app code mirrors
    // at 0x80003180/0x80003194 while building NAS auth fields.
#if defined(MKW_GENERIC_DOL_BOOT)
    constexpr uint32_t kDiscGameCode = RuntimeConfig::GAME_CODE;
    constexpr uint32_t kDiscMakerId = static_cast<uint32_t>(RuntimeConfig::MAKER_CODE) << 16;
#else
    constexpr uint32_t kDiscGameCode = 0x524D4350u; // RMCP
    constexpr uint32_t kDiscMakerId = 0x30310100u;  // 01 + legacy disc/version bytes
#endif
    entries.push_back({0x80000000u, kDiscGameCode, "Disc game code"});
    entries.push_back({0x80000004u, kDiscMakerId, "Disc maker/id"});
#if !WIICOMPILED_GUEST_IS_GAMECUBE
    entries.push_back({0x80003180u, kDiscGameCode, "OS app game code"});
    entries.push_back({0x80003194u, kDiscGameCode, "OS app gamename"});
#endif
    if (RuntimeProduct::IsRetroRewind()) {
        entries.push_back({0x800017D8u, 0x00000001u, "Retro Rewind recomp runtime marker", true});
    }

    for (const auto& reservation : RecompMod::MemoryReservations()) {
        if (reservation.start >= kMem1ArenaLoDefault &&
            reservation.start < mem1ArenaHiDefault &&
            reservation.end <= 0x81800000u) {
            mem1ArenaHiDefault = reservation.start;
            RT_LOG(RT_TAG_MOD) << "Reserved MEM1 range 0x" << std::hex << std::uppercase
                      << reservation.start << "-0x" << reservation.end
                      << " for " << reservation.name
                      << "; MEM1 arena hi now 0x" << mem1ArenaHiDefault
                      << std::dec << std::nouppercase << std::endl;
        }
    }

    // Seed OS clock values used by SDK timing helpers (OSBusClock/OSClock).
    entries.push_back({0x800000F8u, kBusClockHz, "__OSBusClock"});
    entries.push_back({0x800000FCu, kCpuClockHz, "__OSClock"});
    constexpr uint8_t kRegionCode = static_cast<uint8_t>(RuntimeConfig::GAME_CODE & 0xFFu);
    constexpr bool kPalDisc =
        kRegionCode == 'P' || kRegionCode == 'D' || kRegionCode == 'F' ||
        kRegionCode == 'I' || kRegionCode == 'S' || kRegionCode == 'H';
#if WIICOMPILED_GUEST_IS_GAMECUBE
    // Matches the GC BS2 contract used by retail titles: NTSC/PAL selector and
    // 16 MiB main ARAM. GameCube has no IOS or MEM2 low-memory block.
    entries.push_back({0x800000CCu, kPalDisc ? 1u : 0u, "GC VI mode", true});
    entries.push_back({0x800000D0u, 0x01000000u, "GC ARAM size", true});
#else
    // BC/BS2 leaves the active TV standard in low memory for VIConfigure.
    // Direct-DOL Wii boot skips that firmware path, so seed the same contract
    // from the title region. PAL software rejects an NTSC value here before it
    // even reaches the VI register programming path.
    // The shared SC bridge exposes the virtual PAL console with EURGB60 enabled
    // (SCGetEuRgb60Mode() == 1). A real BS2/apploader boot publishes the active
    // TV standard here, and RDSPAF's translated VIInit consumes this word
    // directly: 1 selects PAL50, 5 selects EURGB60. Keep the direct-DOL
    // low-memory contract coherent with the console setting instead of seeding
    // PAL50 while SYSCONF says PAL60.
    entries.push_back({0x800000CCu, kPalDisc ? 5u : 0u, "Wii VI mode", true});
#if defined(MKW_GENERIC_DOL_BOOT)
    if (const auto iosBoot = LoadGenericWiiIosBootState()) {
        entries.push_back({0x80003140u, iosBoot->iosVersion, "IOS version"});
        entries.push_back({0x80003144u, iosBoot->iosDate, "IOS date"});
        // A real apploader publishes an IOS-like version at 0x80003188. Direct
        // DOL boot has no apploader execution, so mirror the active IOS version
        // exactly as Dolphin does for executable direct boots.
        entries.push_back({0x80003188u, iosBoot->iosVersion, "Apploader IOS version"});
        RT_LOG(RT_TAG_RUNTIME) << "Generic Wii boot: TMD requires IOS" << iosBoot->iosNumber
                               << " -> low-memory version 0x" << std::hex << std::uppercase
                               << iosBoot->iosVersion << std::dec << std::nouppercase << std::endl;
    }
#else
    constexpr uint32_t kIos36Version = 0x00240E18u;
    constexpr uint32_t kIos36Date = 0x00030110u;
    entries.push_back({0x80003140u, kIos36Version, "IOS36 version"});
    entries.push_back({0x80003144u, kIos36Date, "IOS36 date"});
#endif
#endif

    if (mem1Size != 0) {
        const uint32_t mem1End = Memory::kMem1CachedBase + mem1Size;
        uint32_t legacyMem1ArenaHi = mem1ArenaHiDefault;
        uint32_t postBootMem1ArenaHi = mem1ArenaHiDefault;
#if defined(MKW_GENERIC_DOL_BOOT)
#if WIICOMPILED_GUEST_IS_GAMECUBE
        if (const auto genericGameCubeBootState = LoadGenericGameCubeBootState(mem1End)) {
            legacyMem1ArenaHi = genericGameCubeBootState->arenaHi;
            postBootMem1ArenaHi = genericGameCubeBootState->arenaHi;
            g_dvdFstReservedBase = genericGameCubeBootState->fstAddress;
            g_dvdFstReservedSize = genericGameCubeBootState->fstMaxSize;
            std::memcpy(Memory::GetPointer(genericGameCubeBootState->fstAddress,
                                           genericGameCubeBootState->fst.size()),
                        genericGameCubeBootState->fst.data(),
                        genericGameCubeBootState->fst.size());
            entries.push_back({0x80000038u, genericGameCubeBootState->fstAddress,
                               "GC FST address", true});
            entries.push_back({0x8000003Cu, genericGameCubeBootState->fstMaxSize,
                               "GC FST max size", true});
            RT_LOG(RT_TAG_RUNTIME) << "Generic GameCube boot metadata -> FST=0x"
                      << std::hex << std::uppercase << genericGameCubeBootState->fstAddress
                      << " size=0x" << genericGameCubeBootState->fst.size()
                      << " max=0x" << genericGameCubeBootState->fstMaxSize
                      << " MEM1 arena hi=0x" << genericGameCubeBootState->arenaHi
                      << std::dec << std::nouppercase << std::endl;
        }
#else
        genericWiiBootState = LoadGenericWiiBootState(mem1End);
        if (genericWiiBootState) {
            legacyMem1ArenaHi = genericWiiBootState->legacyArenaHi;
            postBootMem1ArenaHi = genericWiiBootState->postApploaderArenaHi;
            std::memcpy(Memory::GetPointer(genericWiiBootState->bi2Address,
                                           genericWiiBootState->bi2.size()),
                        genericWiiBootState->bi2.data(), genericWiiBootState->bi2.size());
            entries.push_back({0x800000F4u, genericWiiBootState->bi2Address,
                               "Boot info 2 pointer", true});
            RT_LOG(RT_TAG_RUNTIME) << "Generic Wii boot metadata -> BI2=0x" << std::hex
                      << std::uppercase << genericWiiBootState->bi2Address
                      << " post-apploader MEM1 arena hi=0x"
                      << genericWiiBootState->postApploaderArenaHi
                      << " (FST reserve 0x" << (mem1End - genericWiiBootState->postApploaderArenaHi)
                      << ")" << std::dec << std::nouppercase << std::endl;
        }
#endif
#endif
        entries.push_back({0x80000028u, mem1Size, "Legacy MEM1 size", true});
        entries.push_back({0x80000030u, kMem1ArenaLoDefault, "Legacy MEM1 arena lo", true});
        entries.push_back({0x80000034u, legacyMem1ArenaHi, "Legacy MEM1 arena hi", true});
        entries.push_back({0x800000F0u, mem1Size, "Legacy simulated MEM1 size", true});
#if !WIICOMPILED_GUEST_IS_GAMECUBE
        entries.push_back({0x80003100u, mem1Size, "Physical MEM1 size", true});
        entries.push_back({0x80003104u, mem1Size, "Simulated MEM1 size", true});
        entries.push_back({0x80003108u, mem1End, "MEM1 end", true});
        entries.push_back({0x8000310Cu, kMem1ArenaLoDefault, "MEM1 arena lo", true});
        entries.push_back({0x80003110u, postBootMem1ArenaHi, "MEM1 arena hi", true});
#endif
    }

#if !WIICOMPILED_GUEST_IS_GAMECUBE
    if (mem2Size != 0) {
        const uint32_t physicalMem2End = Memory::kMem2CachedBase + mem2Size;
        const uint32_t iosReservedLo = physicalMem2End - kIosReservedSize;
        const uint32_t mem2End = iosReservedLo;
        const uint32_t ipcBufHi = mem2End;
        const uint32_t ipcBufLo = ipcBufHi - kIPCArenaSize;
        // Reserve FST memory before guest code can use this part of the arena.
        g_dvdFstReservedSize = kDvdFstReserveSize;
        g_dvdFstReservedBase = ipcBufLo - kDvdFstReserveSize;
        const uint32_t mem2ArenaHi = g_dvdFstReservedBase;

        entries.push_back({0x80003118u, mem2Size, "Physical MEM2 size", true});
        entries.push_back({0x8000311Cu, mem2Size, "Simulated MEM2 size", true});
        entries.push_back({0x80003120u, mem2End, "MEM2 end", true});
        entries.push_back({0x80003124u, kMem2LoFloor, "MEM2 arena lo", true});
        entries.push_back({0x80003128u, mem2ArenaHi, "MEM2 arena hi", true});
        entries.push_back({0x80003130u, ipcBufLo, "IPC Buffer lo", true});
        entries.push_back({0x80003134u, ipcBufHi, "IPC Buffer hi", true});
        entries.push_back({0x80003138u, 0x00000002u, "Hollywood revision", true});
        entries.push_back({0x80003148u, iosReservedLo, "IOS reserved lo", true});
        entries.push_back({0x8000314Cu, physicalMem2End, "IOS reserved hi", true});
    }
#endif

    bool patchedAny = false;
    size_t seededCount = 0;
    for (const auto& entry : entries) {
        if (entry.value == 0) continue;
        
        // Only patch if the address is mapped
        if (!Memory::Contains(entry.address, sizeof(uint32_t))) continue;

        // Only patch if currently zero (don't overwrite if OS already initialized)
        if (!entry.force && Memory::Read32(entry.address) != 0) continue;
        
        Memory::Write32(entry.address, entry.value);
        patchedAny = true;
        ++seededCount;
    }

    if (seededCount != 0) {
        RT_LOG(RT_TAG_RUNTIME) << "Seeded " << seededCount << " low-memory default(s)" << std::endl;
    }

    if (patchedAny && mem2Size != 0) {
        const uint32_t patchedLo = Memory::Read32(0x80003124u);
        const uint32_t patchedHi = Memory::Read32(0x80003128u);
        const uint32_t patchedSize = Memory::Read32(0x8000311Cu);
        RT_LOG(RT_TAG_RUNTIME) << "MEM2 defaults active -> size=" << (patchedSize / (1024 * 1024))
                  << " MB, arena 0x" << std::hex << std::uppercase << patchedLo
                  << " - 0x" << patchedHi << std::dec << std::nouppercase << std::endl;
    }
}

const Memory::RegionConfig* SystemBridge::FindRegionConfig(const Memory::Config& config, std::string_view name) {
    for (const auto& region : config.regions) {
        if (region.name == name) {
            return &region;
        }
    }
    return nullptr;
}

void SystemBridge::DumpCpuState(const CpuContext* cpu) {
    DumpCpuState(std::cerr, cpu);
}

void SystemBridge::DumpCpuState(std::ostream& os, const CpuContext* cpu) {
    if (!cpu) {
        os << "[runtime] CPU context unavailable; registers could not be dumped." << std::endl;
        return;
    }

    DumpGuestCrashHints(os, cpu);

    os << "[runtime] PC=0x" << Hex32(cpu->pc)
       << " LR=0x" << Hex32(cpu->lr)
       << " CTR=0x" << Hex32(cpu->ctr)
       << " CR=0x" << Hex32(cpu->cr)
       << " XER=0x" << Hex32(cpu->xer) << std::endl;
    os << "[runtime] SRR0=0x" << Hex32(cpu->srr0)
       << " SRR1=0x" << Hex32(cpu->srr1) << std::endl;
    os << "[runtime] SP(r1)=0x" << Hex32(cpu->gpr[1])
       << " R2=0x" << Hex32(cpu->gpr[2])
       << " R13=0x" << Hex32(cpu->gpr[13]) << std::endl;

    for (int base = 0; base < 32; base += 8) {
        os << "[runtime] GPR" << std::setw(2) << std::setfill('0') << base
           << "-" << std::setw(2) << std::setfill('0') << (base + 7) << ": ";
        for (int i = 0; i < 8; ++i) {
            const int reg = base + i;
            os << "r" << std::setw(2) << std::setfill('0') << reg << "=0x"
               << Hex32(cpu->gpr[reg]) << (i == 7 ? "" : " ");
        }
        os << std::setfill(' ') << std::endl;
    }
    os << std::setfill(' ');
}
